// ─────────────────────────────────────────────
// Mock data and app-wide constants
// ─────────────────────────────────────────────

export const COLORS = {
  primary: '#1890FF',
  primaryLight: '#40A9FF',
  primaryDark: '#096DD9',
  secondary: '#52C41A',
  warning: '#FAAD14',
  danger: '#FF4D4F',
  success: '#52C41A',
  background: '#F5F7FA',
  surface: '#FFFFFF',
  border: '#E8E8E8',
  textPrimary: '#333333',
  textSecondary: '#666666',
  textHint: '#999999',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#D9D9D9',
  lightGray: '#F0F0F0',
};

export const FONT_SIZES = {
  xs: 10,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 18,
  xxl: 22,
  xxxl: 28,
};

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

// ─── Product Categories ───────────────────────
export const CATEGORIES = [
  { id: 'all', name: '全部', icon: '🏪' },
  { id: 'electronics', name: '电子产品', icon: '📱' },
  { id: 'office', name: '办公用品', icon: '🖊️' },
  { id: 'machinery', name: '机械设备', icon: '⚙️' },
  { id: 'chemical', name: '化工原料', icon: '🧪' },
  { id: 'textile', name: '纺织品', icon: '🧵' },
  { id: 'food', name: '食品饮料', icon: '🍱' },
  { id: 'building', name: '建筑材料', icon: '🏗️' },
];

// ─── Suppliers ────────────────────────────────
export const SUPPLIERS = [
  {
    id: 's1',
    name: '深圳科技有限公司',
    region: '广东',
    avatar: 'https://picsum.photos/seed/sup1/60/60',
    verified: true,
    rating: 4.8,
    deals: 3200,
  },
  {
    id: 's2',
    name: '上海办公用品集团',
    region: '上海',
    avatar: 'https://picsum.photos/seed/sup2/60/60',
    verified: true,
    rating: 4.6,
    deals: 1500,
  },
  {
    id: 's3',
    name: '浙江机械制造厂',
    region: '浙江',
    avatar: 'https://picsum.photos/seed/sup3/60/60',
    verified: false,
    rating: 4.3,
    deals: 870,
  },
  {
    id: 's4',
    name: '广州化工原料公司',
    region: '广东',
    avatar: 'https://picsum.photos/seed/sup4/60/60',
    verified: true,
    rating: 4.9,
    deals: 5600,
  },
  {
    id: 's5',
    name: '苏州纺织品贸易',
    region: '江苏',
    avatar: 'https://picsum.photos/seed/sup5/60/60',
    verified: true,
    rating: 4.7,
    deals: 2100,
  },
];

// ─── Products ─────────────────────────────────
export const PRODUCTS = [
  {
    id: 'p1',
    name: '商用笔记本电脑 i7 16G',
    category: 'electronics',
    brand: '联想',
    price: 4999,
    unit: '台',
    minOrder: 5,
    stock: 200,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod1/300/300',
    images: [
      'https://picsum.photos/seed/prod1a/600/600',
      'https://picsum.photos/seed/prod1b/600/600',
      'https://picsum.photos/seed/prod1c/600/600',
    ],
    sales: 1280,
    rating: 4.7,
    description:
      '企业级商用笔记本，搭载英特尔第12代酷睿i7处理器，16GB DDR5内存，512GB SSD固态硬盘。支持Windows 11 Pro系统，适合企业办公、设计、开发等多种场景。',
    specs: [
      { label: '处理器', value: 'Intel Core i7-1260P' },
      { label: '内存', value: '16GB DDR5' },
      { label: '存储', value: '512GB SSD' },
      { label: '显示屏', value: '15.6英寸 FHD 1080P' },
      { label: '操作系统', value: 'Windows 11 Pro' },
      { label: '重量', value: '1.8kg' },
    ],
    tags: ['企业首选', '性价比高'],
  },
  {
    id: 'p2',
    name: '无线商用打印机 A3彩色',
    category: 'electronics',
    brand: '惠普',
    price: 2899,
    unit: '台',
    minOrder: 2,
    stock: 80,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod2/300/300',
    images: [
      'https://picsum.photos/seed/prod2a/600/600',
      'https://picsum.photos/seed/prod2b/600/600',
    ],
    sales: 560,
    rating: 4.5,
    description: 'A3彩色无线打印机，支持双面打印，月打印量高达15000页，适合中大型企业办公室使用。',
    specs: [
      { label: '打印尺寸', value: 'A3' },
      { label: '打印速度', value: '30ppm' },
      { label: '连接方式', value: 'WiFi/USB/以太网' },
      { label: '月打印量', value: '15000页' },
    ],
    tags: ['热销', '企业级'],
  },
  {
    id: 'p3',
    name: '人体工学办公椅 网布',
    category: 'office',
    brand: '冈村',
    price: 1299,
    unit: '把',
    minOrder: 10,
    stock: 500,
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    region: '上海',
    image: 'https://picsum.photos/seed/prod3/300/300',
    images: [
      'https://picsum.photos/seed/prod3a/600/600',
      'https://picsum.photos/seed/prod3b/600/600',
    ],
    sales: 3200,
    rating: 4.8,
    description: '进口人体工学椅，透气网布背部设计，腰托高度可调，座椅角度可调，适合长时间办公使用。',
    specs: [
      { label: '材质', value: '高密度网布' },
      { label: '承重', value: '150kg' },
      { label: '调节范围', value: '腰托/高度/扶手全调节' },
      { label: '颜色', value: '黑色/灰色' },
    ],
    tags: ['爆款', '人体工学'],
  },
  {
    id: 'p4',
    name: 'A4复印纸 80g 10箱',
    category: 'office',
    brand: '绿林',
    price: 280,
    unit: '箱',
    minOrder: 50,
    stock: 10000,
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    region: '上海',
    image: 'https://picsum.photos/seed/prod4/300/300',
    images: ['https://picsum.photos/seed/prod4a/600/600'],
    sales: 12000,
    rating: 4.6,
    description: '80克优质A4复印纸，白度92%，适合激光打印机及复印机使用，每箱5包，每包500张。',
    specs: [
      { label: '规格', value: 'A4 210x297mm' },
      { label: '克重', value: '80g/m²' },
      { label: '白度', value: '92%' },
      { label: '包装', value: '500张/包，5包/箱' },
    ],
    tags: ['批量优惠', '高性价比'],
  },
  {
    id: 'p5',
    name: '工业数控车床 CNC-2000',
    category: 'machinery',
    brand: '大连机床',
    price: 128000,
    unit: '台',
    minOrder: 1,
    stock: 20,
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    region: '浙江',
    image: 'https://picsum.photos/seed/prod5/300/300',
    images: [
      'https://picsum.photos/seed/prod5a/600/600',
      'https://picsum.photos/seed/prod5b/600/600',
      'https://picsum.photos/seed/prod5c/600/600',
    ],
    sales: 45,
    rating: 4.9,
    description: '高精度数控车床，加工精度0.001mm，最大加工直径500mm，适用于轴类、盘类零件加工。',
    specs: [
      { label: '加工精度', value: '0.001mm' },
      { label: '最大转速', value: '4000rpm' },
      { label: '最大加工直径', value: '500mm' },
      { label: '主电机功率', value: '15kW' },
    ],
    tags: ['高精度', '工业级'],
  },
  {
    id: 'p6',
    name: '液压冲压机 200吨',
    category: 'machinery',
    brand: '扬力集团',
    price: 85000,
    unit: '台',
    minOrder: 1,
    stock: 15,
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    region: '浙江',
    image: 'https://picsum.photos/seed/prod6/300/300',
    images: ['https://picsum.photos/seed/prod6a/600/600'],
    sales: 32,
    rating: 4.7,
    description: '200吨液压冲压机，适用于金属冲压、拉伸成型工艺，液压系统稳定可靠。',
    specs: [
      { label: '压力', value: '200吨' },
      { label: '工作台面积', value: '1200x800mm' },
      { label: '液压系统', value: '进口油泵' },
      { label: '电机功率', value: '22kW' },
    ],
    tags: ['重工业', '大吨位'],
  },
  {
    id: 'p7',
    name: '工业盐酸 31% 浓度',
    category: 'chemical',
    brand: '鲁西化工',
    price: 380,
    unit: '吨',
    minOrder: 5,
    stock: 1000,
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod7/300/300',
    images: ['https://picsum.photos/seed/prod7a/600/600'],
    sales: 2800,
    rating: 4.8,
    description: '工业级盐酸，浓度31%，符合GB/T 320-2006国家标准，可用于钢铁酸洗、化学合成等工业用途。',
    specs: [
      { label: '浓度', value: '31%' },
      { label: '执行标准', value: 'GB/T 320-2006' },
      { label: '外观', value: '无色至淡黄色液体' },
      { label: '包装', value: '槽车/IBC桶' },
    ],
    tags: ['工业原料', '大宗商品'],
  },
  {
    id: 'p8',
    name: '环氧树脂 双组分 E51',
    category: 'chemical',
    brand: '南亚化工',
    price: 18000,
    unit: '吨',
    minOrder: 1,
    stock: 200,
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod8/300/300',
    images: ['https://picsum.photos/seed/prod8a/600/600'],
    sales: 420,
    rating: 4.9,
    description: '双酚A型环氧树脂E51，环氧当量185-192g/eq，广泛用于涂料、复合材料、电子封装等领域。',
    specs: [
      { label: '型号', value: 'E51' },
      { label: '环氧当量', value: '185-192g/eq' },
      { label: '粘度(25°C)', value: '12000-18000mPa·s' },
      { label: '包装', value: '200kg/桶' },
    ],
    tags: ['精细化工', '高品质'],
  },
  {
    id: 'p9',
    name: '纯棉面料 32支 坯布',
    category: 'textile',
    brand: '鲁泰',
    price: 12,
    unit: '米',
    minOrder: 1000,
    stock: 500000,
    supplierId: 's5',
    supplierName: '苏州纺织品贸易',
    region: '江苏',
    image: 'https://picsum.photos/seed/prod9/300/300',
    images: [
      'https://picsum.photos/seed/prod9a/600/600',
      'https://picsum.photos/seed/prod9b/600/600',
    ],
    sales: 85000,
    rating: 4.6,
    description: '100%纯棉32支平纹坯布，幅宽160cm，适用于衬衫、内衣、床品等各类服装面料制作。',
    specs: [
      { label: '成分', value: '100%棉' },
      { label: '支数', value: '32支' },
      { label: '幅宽', value: '160cm' },
      { label: '克重', value: '120g/m²' },
    ],
    tags: ['天然棉', '大批量'],
  },
  {
    id: 'p10',
    name: '涤纶速干面料 150D',
    category: 'textile',
    brand: '盛虹纺织',
    price: 8.5,
    unit: '米',
    minOrder: 2000,
    stock: 1000000,
    supplierId: 's5',
    supplierName: '苏州纺织品贸易',
    region: '江苏',
    image: 'https://picsum.photos/seed/prod10/300/300',
    images: ['https://picsum.photos/seed/prod10a/600/600'],
    sales: 120000,
    rating: 4.7,
    description: '150D涤纶速干面料，吸湿排汗，快速干燥，适用于运动服、户外服装制作。',
    specs: [
      { label: '成分', value: '100%涤纶' },
      { label: '规格', value: '150D' },
      { label: '幅宽', value: '150cm' },
      { label: '克重', value: '160g/m²' },
    ],
    tags: ['速干', '运动面料'],
  },
  {
    id: 'p11',
    name: '商用服务器 2U 双路',
    category: 'electronics',
    brand: '华为',
    price: 35000,
    unit: '台',
    minOrder: 1,
    stock: 50,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod11/300/300',
    images: ['https://picsum.photos/seed/prod11a/600/600'],
    sales: 230,
    rating: 4.9,
    description: '企业级2U机架式服务器，双路处理器，支持最大3TB ECC内存，适用于数据中心、云计算等场景。',
    specs: [
      { label: '处理器', value: '双路 Xeon Gold 6230R' },
      { label: '内存', value: '最大3TB DDR4 ECC' },
      { label: '存储', value: '最大25个2.5寸硬盘' },
      { label: '网络', value: '4x 25GE' },
    ],
    tags: ['数据中心', '企业级'],
  },
  {
    id: 'p12',
    name: '智能会议平板 75英寸',
    category: 'electronics',
    brand: '小米',
    price: 12800,
    unit: '台',
    minOrder: 2,
    stock: 30,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod12/300/300',
    images: ['https://picsum.photos/seed/prod12a/600/600'],
    sales: 180,
    rating: 4.6,
    description: '75英寸4K超清会议平板，内置AI摄像头，支持远程视频会议，一触即发，提升会议效率。',
    specs: [
      { label: '尺寸', value: '75英寸' },
      { label: '分辨率', value: '3840x2160 4K' },
      { label: '系统', value: 'Android 9.0' },
      { label: '摄像头', value: '4K广角摄像头' },
    ],
    tags: ['智能会议', '4K显示'],
  },
  {
    id: 'p13',
    name: '不锈钢办公文件柜 四层',
    category: 'office',
    brand: '震旦',
    price: 680,
    unit: '个',
    minOrder: 5,
    stock: 300,
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    region: '上海',
    image: 'https://picsum.photos/seed/prod13/300/300',
    images: ['https://picsum.photos/seed/prod13a/600/600'],
    sales: 2100,
    rating: 4.5,
    description: '四层抽屉式文件柜，304不锈钢材质，防锈防潮，带锁设计保护文件安全。',
    specs: [
      { label: '材质', value: '304不锈钢' },
      { label: '层数', value: '4层' },
      { label: '尺寸', value: '460x620x1320mm' },
      { label: '颜色', value: '银色/黑色' },
    ],
    tags: ['防锈耐用', '带锁安全'],
  },
  {
    id: 'p14',
    name: '工业机械手臂 6轴',
    category: 'machinery',
    brand: '发那科',
    price: 280000,
    unit: '台',
    minOrder: 1,
    stock: 10,
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    region: '浙江',
    image: 'https://picsum.photos/seed/prod14/300/300',
    images: ['https://picsum.photos/seed/prod14a/600/600'],
    sales: 28,
    rating: 4.9,
    description: '6轴工业机械手臂，负载20kg，重复定位精度±0.02mm，适用于焊接、搬运、装配等工序。',
    specs: [
      { label: '轴数', value: '6轴' },
      { label: '最大负载', value: '20kg' },
      { label: '最大臂展', value: '1813mm' },
      { label: '重复精度', value: '±0.02mm' },
    ],
    tags: ['智能制造', '高精度'],
  },
  {
    id: 'p15',
    name: '聚氨酯发泡剂 单组分',
    category: 'chemical',
    brand: '德爱威',
    price: 45,
    unit: '罐',
    minOrder: 200,
    stock: 50000,
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod15/300/300',
    images: ['https://picsum.photos/seed/prod15a/600/600'],
    sales: 8500,
    rating: 4.6,
    description: '单组分聚氨酯发泡剂，750ml/罐，膨胀率高，粘结力强，适用于建筑填缝、隔热保温施工。',
    specs: [
      { label: '规格', value: '750ml/罐' },
      { label: '颜色', value: '淡黄色' },
      { label: '固化时间', value: '表干5min，完全固化12h' },
      { label: '使用温度', value: '+5°C至+40°C' },
    ],
    tags: ['建筑辅材', '批量优惠'],
  },
  {
    id: 'p16',
    name: '真丝绸缎面料 14姆米',
    category: 'textile',
    brand: '达利丝绸',
    price: 85,
    unit: '米',
    minOrder: 100,
    stock: 20000,
    supplierId: 's5',
    supplierName: '苏州纺织品贸易',
    region: '江苏',
    image: 'https://picsum.photos/seed/prod16/300/300',
    images: ['https://picsum.photos/seed/prod16a/600/600'],
    sales: 3600,
    rating: 4.9,
    description: '100%桑蚕丝真丝绸缎，14姆米重量，光泽柔和，手感丝滑，适用于高端服装、领带制作。',
    specs: [
      { label: '成分', value: '100%桑蚕丝' },
      { label: '重量', value: '14姆米' },
      { label: '幅宽', value: '114cm' },
      { label: '颜色', value: '多色可选' },
    ],
    tags: ['高端面料', '纯正蚕丝'],
  },
  {
    id: 'p17',
    name: '商用扫码枪 二维码 USB',
    category: 'electronics',
    brand: '霍尼韦尔',
    price: 420,
    unit: '把',
    minOrder: 10,
    stock: 1000,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod17/300/300',
    images: ['https://picsum.photos/seed/prod17a/600/600'],
    sales: 5600,
    rating: 4.7,
    description: '支持一维/二维条码扫描，USB接口即插即用，适用于超市、仓库、物流等场景。',
    specs: [
      { label: '接口', value: 'USB' },
      { label: '扫描类型', value: '1D/2D条码' },
      { label: '分辨率', value: '800x500像素' },
      { label: '识读速度', value: '>100次/秒' },
    ],
    tags: ['仓储物流', '即插即用'],
  },
  {
    id: 'p18',
    name: '碳酸钙 超细重质 2500目',
    category: 'chemical',
    brand: '正元化工',
    price: 450,
    unit: '吨',
    minOrder: 10,
    stock: 5000,
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod18/300/300',
    images: ['https://picsum.photos/seed/prod18a/600/600'],
    sales: 9200,
    rating: 4.6,
    description: '2500目超细重质碳酸钙，白度98%，纯度99.5%以上，用于涂料、塑料、橡胶等行业填充。',
    specs: [
      { label: '细度', value: '2500目' },
      { label: '白度', value: '98%' },
      { label: '纯度', value: '≥99.5%' },
      { label: '水分', value: '≤0.3%' },
    ],
    tags: ['超细粉体', '大批量'],
  },
  {
    id: 'p19',
    name: '工业缝纫机 高速锁边',
    category: 'machinery',
    brand: '重机',
    price: 3800,
    unit: '台',
    minOrder: 2,
    stock: 120,
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    region: '浙江',
    image: 'https://picsum.photos/seed/prod19/300/300',
    images: ['https://picsum.photos/seed/prod19a/600/600'],
    sales: 780,
    rating: 4.8,
    description: '高速工业锁边缝纫机，最高缝速8000针/分，三线/五线可选，适用于各类服装生产。',
    specs: [
      { label: '最高缝速', value: '8000针/分' },
      { label: '线数', value: '3线/5线' },
      { label: '针距', value: '1.5-4mm' },
      { label: '电机功率', value: '550W' },
    ],
    tags: ['服装工厂', '高速生产'],
  },
  {
    id: 'p20',
    name: '企业级路由器 8口千兆',
    category: 'electronics',
    brand: '华为',
    price: 1280,
    unit: '台',
    minOrder: 3,
    stock: 200,
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    region: '广东',
    image: 'https://picsum.photos/seed/prod20/300/300',
    images: ['https://picsum.photos/seed/prod20a/600/600'],
    sales: 2300,
    rating: 4.8,
    description: '8口千兆企业路由器，支持VLAN划分、QoS控制，双WAN口负载均衡，适用于中小企业组网。',
    specs: [
      { label: 'WAN口', value: '2个千兆' },
      { label: 'LAN口', value: '6个千兆' },
      { label: 'VPN', value: '支持IPSec/SSL VPN' },
      { label: '吞吐量', value: '5Gbps' },
    ],
    tags: ['企业网络', '双WAN口'],
  },
];

// ─── Orders ───────────────────────────────────
export const ORDER_STATUSES = {
  pending: { key: 'pending', label: '待确认', color: '#FAAD14' },
  processing: { key: 'processing', label: '处理中', color: '#1890FF' },
  shipped: { key: 'shipped', label: '已发货', color: '#722ED1' },
  completed: { key: 'completed', label: '已完成', color: '#52C41A' },
  cancelled: { key: 'cancelled', label: '已取消', color: '#FF4D4F' },
};

export const ORDERS = [
  {
    id: 'ORD-2024-001',
    date: '2024-01-15',
    status: 'completed',
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    items: [
      { productId: 'p1', name: '商用笔记本电脑 i7 16G', qty: 10, price: 4999, unit: '台' },
      { productId: 'p17', name: '商用扫码枪 二维码 USB', qty: 20, price: 420, unit: '把' },
    ],
    totalAmount: 58390,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    shippingAddress: '北京市朝阳区建国路89号',
    trackingNumber: 'SF1234567890',
    logisticsCompany: '顺丰速运',
    note: '请尽快安排发货',
  },
  {
    id: 'ORD-2024-002',
    date: '2024-01-20',
    status: 'processing',
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    items: [
      { productId: 'p3', name: '人体工学办公椅 网布', qty: 50, price: 1299, unit: '把' },
      { productId: 'p4', name: 'A4复印纸 80g 10箱', qty: 100, price: 280, unit: '箱' },
      { productId: 'p13', name: '不锈钢办公文件柜 四层', qty: 20, price: 680, unit: '个' },
    ],
    totalAmount: 106550,
    paymentMethod: 'alipay',
    paymentStatus: 'paid',
    shippingAddress: '上海市浦东新区张江高科技园区',
    trackingNumber: 'YT9876543210',
    logisticsCompany: '圆通快递',
    note: '',
  },
  {
    id: 'ORD-2024-003',
    date: '2024-01-25',
    status: 'pending',
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    items: [
      { productId: 'p5', name: '工业数控车床 CNC-2000', qty: 2, price: 128000, unit: '台' },
    ],
    totalAmount: 256000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'unpaid',
    shippingAddress: '浙江省宁波市鄞州区工业园区',
    trackingNumber: '',
    logisticsCompany: '',
    note: '需要上门安装调试',
  },
  {
    id: 'ORD-2024-004',
    date: '2024-02-01',
    status: 'cancelled',
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    items: [
      { productId: 'p7', name: '工业盐酸 31% 浓度', qty: 20, price: 380, unit: '吨' },
    ],
    totalAmount: 7600,
    paymentMethod: 'wechat',
    paymentStatus: 'refunded',
    shippingAddress: '广东省深圳市宝安区工业园',
    trackingNumber: '',
    logisticsCompany: '',
    note: '因供应商无法按期交货，已取消',
  },
  {
    id: 'ORD-2024-005',
    date: '2024-02-05',
    status: 'shipped',
    supplierId: 's5',
    supplierName: '苏州纺织品贸易',
    items: [
      { productId: 'p9', name: '纯棉面料 32支 坯布', qty: 5000, price: 12, unit: '米' },
      { productId: 'p10', name: '涤纶速干面料 150D', qty: 3000, price: 8.5, unit: '米' },
    ],
    totalAmount: 85500,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    shippingAddress: '福建省泉州市晋江市服装工业园',
    trackingNumber: 'ZTO2024020512345',
    logisticsCompany: '中通快递',
    note: '面料请卷装发货',
  },
  {
    id: 'ORD-2024-006',
    date: '2024-02-10',
    status: 'processing',
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    items: [
      { productId: 'p11', name: '商用服务器 2U 双路', qty: 5, price: 35000, unit: '台' },
      { productId: 'p20', name: '企业级路由器 8口千兆', qty: 10, price: 1280, unit: '台' },
    ],
    totalAmount: 187800,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    shippingAddress: '北京市西城区金融街35号',
    trackingNumber: 'SF2024021098765',
    logisticsCompany: '顺丰速运',
    note: '设备到货后需要IT工程师现场配置',
  },
  {
    id: 'ORD-2024-007',
    date: '2024-02-15',
    status: 'pending',
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    items: [
      { productId: 'p8', name: '环氧树脂 双组分 E51', qty: 5, price: 18000, unit: '吨' },
      { productId: 'p15', name: '聚氨酯发泡剂 单组分', qty: 500, price: 45, unit: '罐' },
    ],
    totalAmount: 112500,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'unpaid',
    shippingAddress: '江苏省南京市江宁区新港开发区',
    trackingNumber: '',
    logisticsCompany: '',
    note: '危化品运输需提前确认资质',
  },
  {
    id: 'ORD-2024-008',
    date: '2024-02-20',
    status: 'completed',
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    items: [
      { productId: 'p4', name: 'A4复印纸 80g 10箱', qty: 200, price: 280, unit: '箱' },
    ],
    totalAmount: 56000,
    paymentMethod: 'alipay',
    paymentStatus: 'paid',
    shippingAddress: '广东省广州市天河区员村四横路',
    trackingNumber: 'JD2024022088888',
    logisticsCompany: '京东物流',
    note: '',
  },
  {
    id: 'ORD-2024-009',
    date: '2024-02-25',
    status: 'shipped',
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    items: [
      { productId: 'p19', name: '工业缝纫机 高速锁边', qty: 20, price: 3800, unit: '台' },
    ],
    totalAmount: 76000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    shippingAddress: '广东省广州市花都区狮岭镇',
    trackingNumber: 'SF2024022556789',
    logisticsCompany: '顺丰速运',
    note: '',
  },
  {
    id: 'ORD-2024-010',
    date: '2024-03-01',
    status: 'pending',
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    items: [
      { productId: 'p12', name: '智能会议平板 75英寸', qty: 5, price: 12800, unit: '台' },
      { productId: 'p2', name: '无线商用打印机 A3彩色', qty: 5, price: 2899, unit: '台' },
    ],
    totalAmount: 78495,
    paymentMethod: 'wechat',
    paymentStatus: 'unpaid',
    shippingAddress: '四川省成都市高新区天府大道北段',
    trackingNumber: '',
    logisticsCompany: '',
    note: '设备需要到付款后才发货',
  },
];

// ─── Chat Conversations ───────────────────────
export const CHAT_CONVERSATIONS = [
  {
    id: 'chat1',
    supplierId: 's1',
    supplierName: '深圳科技有限公司',
    supplierAvatar: 'https://picsum.photos/seed/sup1/60/60',
    lastMessage: '好的，我们可以为您提供批量折扣，10台起可以优惠8%',
    lastMessageTime: '14:32',
    unreadCount: 2,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: '你好，请问笔记本电脑批量采购有折扣吗？',
        time: '14:28',
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 's1',
        text: '您好！欢迎咨询，我们的企业采购政策如下：5-9台95折，10台及以上92折，50台以上可进一步协商。',
        time: '14:30',
        type: 'text',
      },
      {
        id: 'm3',
        senderId: 'user',
        text: '我们计划采购15台，请报一下详细价格',
        time: '14:31',
        type: 'text',
      },
      {
        id: 'm4',
        senderId: 's1',
        text: '好的，我们可以为您提供批量折扣，10台起可以优惠8%',
        time: '14:32',
        type: 'text',
      },
    ],
  },
  {
    id: 'chat2',
    supplierId: 's2',
    supplierName: '上海办公用品集团',
    supplierAvatar: 'https://picsum.photos/seed/sup2/60/60',
    lastMessage: '已为您安排发货，预计3-5个工作日到达',
    lastMessageTime: '昨天',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: '请问ORD-2024-002什么时候发货？',
        time: '昨天 10:00',
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 's2',
        text: '您好，您的订单已在生产中，预计明天可以安排发货。',
        time: '昨天 10:15',
        type: 'text',
      },
      {
        id: 'm3',
        senderId: 'user',
        text: '好的，请尽快安排',
        time: '昨天 10:20',
        type: 'text',
      },
      {
        id: 'm4',
        senderId: 's2',
        text: '已为您安排发货，预计3-5个工作日到达',
        time: '昨天 16:45',
        type: 'text',
      },
    ],
  },
  {
    id: 'chat3',
    supplierId: 's3',
    supplierName: '浙江机械制造厂',
    supplierAvatar: 'https://picsum.photos/seed/sup3/60/60',
    lastMessage: '数控车床的安装调试需要2名工程师，请提前预约场地',
    lastMessageTime: '周一',
    unreadCount: 1,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: '请问CNC-2000数控车床需要什么安装条件？',
        time: '周一 09:30',
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 's3',
        text: '设备安装需要：1. 平整混凝土地面，承重≥2吨/平方米；2. 电源：三相380V，50A；3. 通风良好；4. 设备尺寸：3200x1800x2100mm',
        time: '周一 09:45',
        type: 'text',
      },
      {
        id: 'm3',
        senderId: 's3',
        text: '数控车床的安装调试需要2名工程师，请提前预约场地',
        time: '周一 09:46',
        type: 'text',
      },
    ],
  },
  {
    id: 'chat4',
    supplierId: 's4',
    supplierName: '广州化工原料公司',
    supplierAvatar: 'https://picsum.photos/seed/sup4/60/60',
    lastMessage: '危化品运输需要您提供危险货物道路运输许可证复印件',
    lastMessageTime: '周三',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: '你好，我们想采购工业盐酸，请问运输有什么要求？',
        time: '周三 14:00',
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 's4',
        text: '您好！工业盐酸属于危险化学品，运输需要专用槽车，我们有自有物流可以承接。',
        time: '周三 14:10',
        type: 'text',
      },
      {
        id: 'm3',
        senderId: 's4',
        text: '危化品运输需要您提供危险货物道路运输许可证复印件',
        time: '周三 14:11',
        type: 'text',
      },
    ],
  },
  {
    id: 'chat5',
    supplierId: 's5',
    supplierName: '苏州纺织品贸易',
    supplierAvatar: 'https://picsum.photos/seed/sup5/60/60',
    lastMessage: '我们可以免费提供面料样品，请告知您的地址',
    lastMessageTime: '上周五',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: '你好，我想了解你们的纯棉面料，可以先寄样品看看吗？',
        time: '上周五 11:00',
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 's5',
        text: '您好！当然可以，我们提供免费样品服务，可提供10x10cm的色卡样本。',
        time: '上周五 11:20',
        type: 'text',
      },
      {
        id: 'm3',
        senderId: 's5',
        text: '我们可以免费提供面料样品，请告知您的地址',
        time: '上周五 11:21',
        type: 'text',
      },
    ],
  },
];

// ─── Sort Options ────────────────────────────
export const SORT_OPTIONS = [
  { key: 'default', label: '综合排序' },
  { key: 'price_asc', label: '价格从低到高' },
  { key: 'price_desc', label: '价格从高到低' },
  { key: 'sales', label: '销量优先' },
  { key: 'rating', label: '评分优先' },
];

// ─── Regions ──────────────────────────────────
export const REGIONS = [
  { id: 'all', name: '全部地区' },
  { id: '广东', name: '广东' },
  { id: '上海', name: '上海' },
  { id: '浙江', name: '浙江' },
  { id: '江苏', name: '江苏' },
  { id: '北京', name: '北京' },
  { id: '福建', name: '福建' },
  { id: '四川', name: '四川' },
];

// ─── Brands ───────────────────────────────────
export const BRANDS = [
  { id: 'all', name: '全部品牌' },
  { id: '联想', name: '联想' },
  { id: '华为', name: '华为' },
  { id: '惠普', name: '惠普' },
  { id: '小米', name: '小米' },
  { id: '冈村', name: '冈村' },
  { id: '震旦', name: '震旦' },
  { id: '发那科', name: '发那科' },
  { id: '重机', name: '重机' },
  { id: '鲁西化工', name: '鲁西化工' },
  { id: '南亚化工', name: '南亚化工' },
  { id: '鲁泰', name: '鲁泰' },
  { id: '达利丝绸', name: '达利丝绸' },
];

// ─── Payment Methods ─────────────────────────
export const PAYMENT_METHODS = [
  { key: 'bank_transfer', label: '银行转账', icon: '🏦' },
  { key: 'alipay', label: '支付宝', icon: '💙' },
  { key: 'wechat', label: '微信支付', icon: '💚' },
];

export const CURRENT_USER = {
  id: 'u1',
  name: '张明',
  company: '北京创新科技有限公司',
  phone: '13800138000',
  email: 'zhangming@bjcxtech.com',
  avatar: 'https://picsum.photos/seed/user1/100/100',
  address: '北京市朝阳区建国路89号华贸中心',
  role: '采购经理',
  memberLevel: '钻石会员',
};
